- name: Install and run Nginx
  hosts: web  # Replace 'web' with your actual group of hosts from the inventory
  become: true  # Elevate privileges to install packages
  tasks: 
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
