---
- name: variables from files
  hosts: localhost
  vars_files:
    - variable.yaml
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: "Hello, I am learning {{ NAME }}, Trainer is {{ TRAINER }}, Course duration is {{ DURATION }}"
