- name: varibles from files
  hosts: local host
  vars_files:
  - variable.yaml
  tasks:
  - name: printing variable
     ansible.builtin.debug:
       msg: "hellow i am learning {{NAME}}, Trainer is {{TRAINER}}, Course is {{DURATION}}"

