---
- name: variable from prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: "Please enter the username"
      private: false # you can see the values entered on screen
    - name: PASSWORD
      prompt: "Please enter the password"
      private: true # you can't see the values entered on screen
  tasks:
    - name: print the variable values
      ansible.builtin.debug:
        msg: "USERNAME: {{ USERNAME }}, Password: {{ PASSWORD }}"
