- name: vsribles form command line
  hosts: localhosts
  tasks:
   - name: print the varibles from command line
     ansible.builtin.debug:
      msg: "the Value of varible course is {{COURSE}}"
     