---
- name: Loops in Ansible
  hosts: localhost
  tasks:
    - name: Print the name
      ansible.builtin.debug:
        msg: "hello {{ item }}"
      loop:
        - sankar
        - akhila
        - chalapathi
        - bhavani
