- name: Installing packages
  hosts: mongodb
  become: yes
  tasks:
    - name: Install the packages
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{item.state}"
      loop:
        - {name: 'nginx', state: 'absent'}
        - {name: 'postfix', state: 'installed'}
        - {name: 'cyrus-sasl-plain', state: 'absent'}
        - {name: 'mail', state: 'installed'}
        