- name: demo on functions are filters
  hosts: local
  connection: local
  tasks:
   - name: print the varibles on un defined
     ansible.builtin.debug:
     msg: "Hello {{Course | default (Ansible)}}"