  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "sivakumar reddy"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { "key": "name","value": "DevOps with AWS" }
      - { "key": "duration","value": 120 }
      - { "key": "trainer","value": "sivakumar reddy" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"