- name: create the ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
   subnet_id:
   sg_id:
   ami_id:
   instances:
    - mysql
    - frontend
    - backend
  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
      name: "{{ iteam }}"
       vpc_subnet_id: "{{ subnet_id }}"
       instance_type: "t3.micro"
       security_group: "{{ sg_id }}"
       image_id:        "{{ ami_id }}"
    loop: "{{ instances }}"   
    register: ec2_instances
 