- name: create the ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
   subnet_id: "subnet-0702410f643aaa623"
   sg_id:     "sg-03febb88e29aa29cd"
   ami_id:    "ami-09c813fb71547fc4f"
   zone:      "joinsankardevops.online"
   instances:
    - mysql
    - frontend
    - backend
  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id:        "{{ ami_id }}"
     loop: "{{ instances }}"   
     register: ec2_instances

   - name : print the ec2-instances
     ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
 #private ip  
   - name: create R53 records
     community.aws.route53:
      zone: "{{ zone }}"
      state: present  
      type:  A
      record: "{{ item.item }}.{{ zone }}"
      value: "{{ item.instances[0].public_ip_address }}"
      ttl: 1
      wait: true
      overwrite: true
     loop: "{{ ec2_instances.results }}" 

#public ip

   - name: create R53 records
     community.aws.route53:
      zone: "{{ zone }}"
      state: present  
      type:  A
      record: "{{ zone }}"
      value: "{{ item.instances[0].public_ip_address }}"
      ttl: 1
      wait: true
      overwrite: true
     loop: "{{ ec2_instances.results }}" 
     when: item.item == "frontend"



 